# Configuration for processing ROS2 bag files

# Path to the input ROS2 bag file
bag_path: "/opt/ros_ws/rosbags/ROSBAG.mcap"

# Directory where the exported data will be saved
output_dir: "/opt/ros_ws/output/"

storage_id: "mcap"

# List of topics to extract from the ROS2 bag
topics:
  # Configuration for the point cloud topic
  - name: "/sensor/lidar/top/points"  # 10Hz
    type: "PointCloud2"
    sample_interval: 1                # 10Hz

  # Configuration for the RGB image topic
  - name: "/sensor/camera/fsp_l/image_rect_color/compressed"  # 20Hz
    type: "CompressedImage"
    encoding: "rgb8"
    sample_interval: 1                                        # 10Hz

  # Configuration for the RGB image topic
  - name: "/sensor/camera/rsp_l/image_rect_color/compressed"  # 20Hz
    type: "CompressedImage"
    encoding: "rgb8"
    sample_interval: 1                                        # 10Hz

  # Configuration for the RGB image topic
  - name: "/sensor/camera/lspf_r/image_rect_color/compressed"  # 20Hz
    type: "CompressedImage"
    encoding: "rgb8"
    sample_interval: 1                                        # 10Hz

  # Configuration for the RGB image topic
  - name: "/sensor/camera/lspr_l/image_rect_color/compressed"  # 20Hz
    type: "CompressedImage"
    encoding: "rgb8"
    sample_interval: 1                                        # 10Hz

  # Configuration for the RGB image topic
  - name: "/sensor/camera/rspf_l/image_rect_color/compressed"  # 20Hz
    type: "CompressedImage"
    encoding: "rgb8"
    sample_interval: 1                                        # 10Hz

  # Configuration for the RGB image topic
  - name: "/sensor/camera/rspr_r/image_rect_color/compressed"  # 20Hz
    type: "CompressedImage"
    encoding: "rgb8"
    sample_interval: 1                                        # 10Hz
