name: Pre-commit

on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    uses: ./.github/workflows/reusable-update-pre-commit.yml
    secrets:
      precommit-pr-token: ${{ secrets.PRECOMMIT_AUTOUPDATE_PR_TOKEN }}
